---
title: "Gov 50 Final Project"
author: "Lauren Cruickshank"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to college admission statistics in correlation with race. I would like to focus on undergraduate colleges. I would like to potentially compare college in America from different regions. 



My research question is " Does the Race Diversity of Public-Four-Year Colleges match the Race Diversity of their state? It is my hypothesis that very little of the states will actually match the diversity between college students and state population. There are several reasons that I think this may be, the main one being access to having quality education that leads to proper college preparation. In states that have a more diverse state population, I expect to see a more diverse college population and the contrary with states that have less diverse population. The comparison of whether a state is diverse or not diverse will be by comparing their racial population during the time period to the racial population of the United States as a whole. My dataset is comprised of the state and the percentage of each race group during the year 2018-2019. The difference in percentages between state and college will be found and those will be compared among the states. What will be measured is how large the difference is between states. If I observe greater rates of differences between the data it will support my thesis but if I do not my thesis will be incorrect.